### ISSUE TITLE
Opal Roadmap (for 1.0.0)

### ISSUE THREAD

**Issue by adambeynon** [opal/opal#279]
Edit:

The roadmap is now adjusted for 1.0.0. We need to decide what is required for that release, and what is required for 1.1.0.
- [x] source maps
- [x] make Parser easier to subclass for custom build targets (sprockets, node, browser)
- [x] use mspec for running tests
- [x] use specs from rubyspec and remove our current "duplication" of rubyspecs

**Comment by zw963** [comment]
Congratulation! 

1.0 is released!
